### ISSUE TITLE
Similar goals / precisions

### ISSUE THREAD

**Issue by romainreuillon** [aecor/liberator#2]
Great lib. I have been trying to do something slightly similar:
https://github.com/ISCPIF/freedsl

One thing I don't understand from your example is how the interpreter is derived. Would you mind to explain?

**Comment by notxcain** [comment]
@romainreuillon thanks! Interpreter for a single free AST is created using macro-generated function (see, `toFunctionK` in example). If you pass it an instance of your `Foo[F]` you'll get `FooFree ~> F`, which is interpreter.

**Comment by notxcain** [comment]
@romainreuillon I'm closing this issue, if you have more questions please welcome to [Gitter](https://gitter.im/aecor/liberator)!

**Comment by romainreuillon** [comment]
Thanks for you answer. I've planned to look a bit more into your code as soon as I find some free time.
